services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sistem_pagaruyung_aki_mart
    container_name: sistem_pagaruyung_aki_mart
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
